<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <EnablePackageVersionOverride>false</EnablePackageVersionOverride>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.28" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="8.0.28" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />
    <PackageVersion Include="AutoMapper" Version="16.2.0" />
    <PackageVersion Include="AutoMapper.Extensions.EnumMapping" Version="6.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authorization" Version="8.0.28" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity" Version="2.3.12" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Identity.Stores" Version="8.0.28" />
    <PackageVersion Include="Microsoft.IdentityModel.Tokens" Version="8.22.0" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
    <PackageVersion Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.0.0" />
    <PackageVersion Include="Asp.Versioning.Mvc" Version="8.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.28" />
    <PackageVersion Include="Microsoft.AspNetCore.Diagnostics" Version="2.3.12" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.FileExtensions" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="8.0.0" />

  </ItemGroup>

</Project>
