name: hanamilegal-web

services:
  frontend:
    container_name: Hanamilegal.Web.Frontend
    image: hanamilegal-web-frontend:latest
    build:
      context: ./Applications/Hanamilegal.Web.Frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 512M
    volumes:
      - ./Certs/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - ./Certs/privkey.pem:/etc/ssl/private/privkey.pem:ro
