name: hanamilegal-web

services:
  frontend:
    container_name: Hanamilegal.Web.Frontend
    image: hanamilegal-web-frontend-dev:latest
    build:
      context: ./Applications/Hanamilegal.Web.Frontend
      dockerfile: Dockerfile.dev
      args:
        VITE_PORT: 8080
    ports:
      - 8080:8080
    restart: on-failure
