name: hanamilegal-web

services:
  legal-support-app:
    container_name: Hanamilegal.Web.LegalSupportApp
    image: hanamilegal-web-legal-support-app:latest
    restart: on-failure
    build:
      context: ./Applications/Hanamilegal.Web.LegalSupportApp
      dockerfile: Dockerfile
      args:
        VITE_COOKIE_POLICY_NAME: ${LEGAL_SUPPORT_APP_COOKIE_POLICY_NAME}
        VITE_PRIVACY_POLICY_NAME: ${LEGAL_SUPPORT_APP_PRIVACY_POLICY_NAME}
        VITE_APPLICATIONS_API_BASE_URL: ${APPLICATIONS_API_BASE_URL}
    depends_on:
      - applications-api
    expose:
      - 80
    deploy:
      resources:
        limits:
          cpus: 0.4
          memory: 256M
    volumes:
      - ${LEGAL_SUPPORT_APP_DOCS_HOST_PATH}:/usr/share/nginx/html/docs:ro

  internal-app:
    container_name: Hanamilegal.Web.InternalApp
    image: hanamilegal-web-internal-app:latest
    restart: on-failure
    build:
      context: ./
      dockerfile: ./Applications/Hanamilegal.Web.InternalApp/Dockerfile
    depends_on:
      - accounts-api
      - applications-api
    expose:
      - 80
    environment:
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Production
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__ExpireMinutes: ${JWT_EXPIRE_MINUTES}
      Jwt__ClockSkewSeconds: ${JWT_CLOCK_SKEW_SECONDS}
    deploy:
      resources:
        limits:
          cpus: 0.4
          memory: 512M
    volumes:
      - internal-app-keys:/Keys

  tech-app:
    container_name: Hanamilegal.Web.TechApp
    image: hanamilegal-web-tech-app:latest
    restart: on-failure
    build:
      context: ./Applications/Hanamilegal.Web.TechApp
      dockerfile: Dockerfile
    expose:
      - 80
    deploy:
      resources:
        limits:
          cpus: 0.4
          memory: 256M

  proxy:
    container_name: Proxy
    image: nginx:stable-alpine
    restart: on-failure
    depends_on:
      - legal-support-app
      - internal-app
      - tech-app
    ports:
      - 80:80
      - 443:443
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: 64M
    volumes:
      - ./Proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./Certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./Certs/privkey.pem:/etc/nginx/certs/privkey.pem:ro

  accounts-api:
    container_name: Hanamilegal.Web.AccountsApi
    image: hanamilegal-web-accounts-api:latest
    restart: on-failure
    build:
      context: ./
      dockerfile: ./Api/Hanamilegal.Web.AccountsApi/Dockerfile
    depends_on:
      - accounts-db
    expose:
      - 80
    environment:
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__AccountsDb: >-
        Host=accounts-db;
        Port=5432;
        Database=${ACCOUNTS_DB_NAME};
        Username=${ACCOUNTS_DB_USER};
        Password=${ACCOUNTS_DB_PASSWORD}
      InitialUsers__Users__0__Email: ${ACCOUNTS_DB_INIT_USER_EMAIL}
      InitialUsers__Users__0__Password: ${ACCOUNTS_DB_INIT_USER_PASSWORD}
      InitialUsers__Users__0__Role: ${ACCOUNTS_DB_INIT_USER_ROLE}
      InitialUsers__Users__1__Email: ${ACCOUNTS_DB_INIT_APPLICATION_VIEWER_EMAIL}
      InitialUsers__Users__1__Password: ${ACCOUNTS_DB_INIT_APPLICATION_VIEWER_PASSWORD}
      InitialUsers__Users__1__Role: ${ACCOUNTS_DB_INIT_APPLICATION_VIEWER_ROLE}
      InitialUsers__Users__2__Email: ${ACCOUNTS_DB_INIT_ADMIN_EMAIL}
      InitialUsers__Users__2__Password: ${ACCOUNTS_DB_INIT_ADMIN_PASSWORD}
      InitialUsers__Users__2__Role: ${ACCOUNTS_DB_INIT_ADMIN_ROLE}
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__ExpireMinutes: ${JWT_EXPIRE_MINUTES}
      Jwt__ClockSkewSeconds: ${JWT_CLOCK_SKEW_SECONDS}
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: 128M

  applications-api:
    container_name: Hanamilegal.Web.ApplicationsApi
    image: hanamilegal-web-applications-api:latest
    restart: on-failure
    build:
      context: ./
      dockerfile: ./Api/Hanamilegal.Web.ApplicationsApi/Dockerfile
    depends_on:
      - applications-db
    expose:
      - 80
    environment:
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__ApplicationsDb: >-
        Host=applications-db;
        Port=5432;
        Database=${APPLICATIONS_DB_NAME};
        Username=${APPLICATIONS_DB_USER};
        Password=${APPLICATIONS_DB_PASSWORD}
      ConnectionStrings__ConsentsDb: mongodb://${CONSENTS_DB_USER}:${CONSENTS_DB_PASSWORD}@consents-db:27017/${CONSENTS_DB_NAME}?authSource=admin
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__ExpireMinutes: ${JWT_EXPIRE_MINUTES}
      Jwt__ClockSkewSeconds: ${JWT_CLOCK_SKEW_SECONDS}
      Path__Documents: ${LEGAL_SUPPORT_APP_DOCS_CONTAINER_PATH}
      FileName__CookiePolicyName: ${LEGAL_SUPPORT_APP_COOKIE_POLICY_NAME}
      FileName__CookiePolicyManifestName: ${LEGAL_SUPPORT_APP_COOKIE_POLICY_MANIFEST_NAME}
      FileName__PrivacyPolicyName: ${LEGAL_SUPPORT_APP_PRIVACY_POLICY_NAME}
      FileName__PrivacyPolicyManifestName: ${LEGAL_SUPPORT_APP_PRIVACY_POLICY_MANIFEST_NAME}
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: 128M
    volumes:
      - ${LEGAL_SUPPORT_APP_DOCS_HOST_PATH}:${LEGAL_SUPPORT_APP_DOCS_CONTAINER_PATH}:ro

  accounts-db:
    container_name: AccountsDb
    image: postgres:18
    restart: on-failure
    expose:
      - 5432
    environment:
      POSTGRES_DB: ${ACCOUNTS_DB_NAME}
      POSTGRES_USER: ${ACCOUNTS_DB_USER}
      POSTGRES_PASSWORD: ${ACCOUNTS_DB_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: 128M
    volumes:
      # In postgres 18+ /var/lib/postgresql/data moved to /var/lib/postgresql
      - accounts-db-data:/var/lib/postgresql

  applications-db:
    container_name: ApplicationsDb
    image: postgres:18
    restart: on-failure
    expose:
      - 5432
    environment:
      POSTGRES_DB: ${APPLICATIONS_DB_NAME}
      POSTGRES_USER: ${APPLICATIONS_DB_USER}
      POSTGRES_PASSWORD: ${APPLICATIONS_DB_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: 128M
    volumes:
      # In postgres 18+ /var/lib/postgresql/data moved to /var/lib/postgresql
      - applications-db-data:/var/lib/postgresql

  consents-db:
    container_name: ConsentsDb
    image: mongo:8
    restart: on-failure
    expose:
      - 27017
    environment:
      MONGO_INITDB_DATABASE: ${CONSENTS_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${CONSENTS_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${CONSENTS_DB_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: 128M
    volumes:
      - consents-db-data:/data/db

volumes:
  accounts-db-data:
  applications-db-data:
  consents-db-data:
  internal-app-keys:
