name: hanamilegal-web

services:
  legal-support-app:
    container_name: Hanamilegal.Web.LegalSupportApp
    image: hanamilegal-web-legal-support-app-dev:latest
    restart: on-failure
    build:
      context: ./Applications/Hanamilegal.Web.LegalSupportApp
      dockerfile: Dockerfile.dev
    depends_on:
      - applications-api
    ports:
      - 8080:8080
    environment:
      VITE_PORT: 8080
      VITE_COOKIE_POLICY_NAME: ${LEGAL_SUPPORT_APP_COOKIE_POLICY_NAME}
      VITE_PRIVACY_POLICY_NAME: ${LEGAL_SUPPORT_APP_PRIVACY_POLICY_NAME}
      VITE_APPLICATIONS_API_BASE_URL: /applications-api
    volumes:
      - ${LEGAL_SUPPORT_APP_DOCS_HOST_PATH}:/app/public/docs:ro

  internal-app:
    container_name: Hanamilegal.Web.InternalApp
    image: hanamilegal-web-internal-app-dev:latest
    restart: on-failure
    build:
      context: ./
      dockerfile: ./Applications/Hanamilegal.Web.InternalApp/Dockerfile.dev
    depends_on:
      - accounts-api
      - applications-api
    ports:
      - 8081:443
    environment:
      ASPNETCORE_URLS: https://+:443
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_Kestrel__Certificates__Default__Path: /etc/ssl/certs/fullchain.pem
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /etc/ssl/private/privkey.pem
      # ASPNETCORE_Kestrel__Certificates__Default__Password: ${CERT_PASSWORD}
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__ExpireMinutes: ${JWT_EXPIRE_MINUTES}
      Jwt__ClockSkewSeconds: ${JWT_CLOCK_SKEW_SECONDS}
    volumes:
      - ./Certs/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - ./Certs/privkey.pem:/etc/ssl/private/privkey.pem:ro
      - internal-app-keys:/Keys

  tech-app:
    container_name: Hanamilegal.Web.TechApp
    image: hanamilegal-web-tech-app-dev:latest
    restart: on-failure
    build:
      context: ./Applications/Hanamilegal.Web.TechApp
      dockerfile: Dockerfile.dev
    ports:
      - 8082:8082
    environment:
      VITE_PORT: 8082

  accounts-api:
    container_name: Hanamilegal.Web.AccountsApi
    image: hanamilegal-web-accounts-api-dev:latest
    restart: on-failure
    build:
      context: ./
      dockerfile: ./Api/Hanamilegal.Web.AccountsApi/Dockerfile.dev
    depends_on:
      - accounts-db
    expose:
      - 80
    environment:
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__AccountsDb: >-
        Host=accounts-db;
        Port=5432;
        Database=${ACCOUNTS_DB_NAME};
        Username=${ACCOUNTS_DB_USER};
        Password=${ACCOUNTS_DB_PASSWORD}
      InitialUsers__Users__0__Email: ${ACCOUNTS_DB_INIT_USER_EMAIL}
      InitialUsers__Users__0__Password: ${ACCOUNTS_DB_INIT_USER_PASSWORD}
      InitialUsers__Users__0__Role: ${ACCOUNTS_DB_INIT_USER_ROLE}
      InitialUsers__Users__1__Email: ${ACCOUNTS_DB_INIT_APPLICATION_VIEWER_EMAIL}
      InitialUsers__Users__1__Password: ${ACCOUNTS_DB_INIT_APPLICATION_VIEWER_PASSWORD}
      InitialUsers__Users__1__Role: ${ACCOUNTS_DB_INIT_APPLICATION_VIEWER_ROLE}
      InitialUsers__Users__2__Email: ${ACCOUNTS_DB_INIT_ADMIN_EMAIL}
      InitialUsers__Users__2__Password: ${ACCOUNTS_DB_INIT_ADMIN_PASSWORD}
      InitialUsers__Users__2__Role: ${ACCOUNTS_DB_INIT_ADMIN_ROLE}
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__ExpireMinutes: ${JWT_EXPIRE_MINUTES}
      Jwt__ClockSkewSeconds: ${JWT_CLOCK_SKEW_SECONDS}

  applications-api:
    container_name: Hanamilegal.Web.ApplicationsApi
    image: hanamilegal-web-applications-api-dev:latest
    restart: on-failure
    build:
      context: ./
      dockerfile: ./Api/Hanamilegal.Web.ApplicationsApi/Dockerfile.dev
    depends_on:
      - applications-db
    expose:
      - 80
    environment:
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__ApplicationsDb: >-
        Host=applications-db;
        Port=5432;
        Database=${APPLICATIONS_DB_NAME};
        Username=${APPLICATIONS_DB_USER};
        Password=${APPLICATIONS_DB_PASSWORD}
      ConnectionStrings__ConsentsDb: mongodb://${CONSENTS_DB_USER}:${CONSENTS_DB_PASSWORD}@consents-db:27017/${CONSENTS_DB_NAME}?authSource=admin
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__ExpireMinutes: ${JWT_EXPIRE_MINUTES}
      Jwt__ClockSkewSeconds: ${JWT_CLOCK_SKEW_SECONDS}
      Path__Documents: ${LEGAL_SUPPORT_APP_DOCS_CONTAINER_PATH}
      FileName__CookiePolicyName: ${LEGAL_SUPPORT_APP_COOKIE_POLICY_NAME}
      FileName__CookiePolicyManifestName: ${LEGAL_SUPPORT_APP_COOKIE_POLICY_MANIFEST_NAME}
      FileName__PrivacyPolicyName: ${LEGAL_SUPPORT_APP_PRIVACY_POLICY_NAME}
      FileName__PrivacyPolicyManifestName: ${LEGAL_SUPPORT_APP_PRIVACY_POLICY_MANIFEST_NAME}
    volumes:
      - ${LEGAL_SUPPORT_APP_DOCS_HOST_PATH}:${LEGAL_SUPPORT_APP_DOCS_CONTAINER_PATH}:ro

  accounts-db:
    container_name: AccountsDb
    image: postgres:18
    restart: on-failure
    expose:
      - 5432
    environment:
      POSTGRES_DB: ${ACCOUNTS_DB_NAME}
      POSTGRES_USER: ${ACCOUNTS_DB_USER}
      POSTGRES_PASSWORD: ${ACCOUNTS_DB_PASSWORD}
    volumes:
      # In postgres 18+ /var/lib/postgresql/data moved to /var/lib/postgresql
      - accounts-db-data:/var/lib/postgresql

  applications-db:
    container_name: ApplicationsDb
    image: postgres:18
    restart: on-failure
    expose:
      - 5432
    environment:
      POSTGRES_DB: ${APPLICATIONS_DB_NAME}
      POSTGRES_USER: ${APPLICATIONS_DB_USER}
      POSTGRES_PASSWORD: ${APPLICATIONS_DB_PASSWORD}
    volumes:
      # In postgres 18+ /var/lib/postgresql/data moved to /var/lib/postgresql
      - applications-db-data:/var/lib/postgresql

  consents-db:
    container_name: ConsentsDb
    image: mongo:8
    restart: on-failure
    expose:
      - 27017
    environment:
      MONGO_INITDB_DATABASE: ${CONSENTS_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${CONSENTS_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${CONSENTS_DB_PASSWORD}
    volumes:
      - consents-db-data:/data/db

volumes:
  accounts-db-data:
  applications-db-data:
  consents-db-data:
  internal-app-keys:
