FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Configure environment
ARG APPLICATIONS_DB_CONNECTION_STRING
ENV APPLICATIONS_DB_CONNECTION_STRING="$APPLICATIONS_DB_CONNECTION_STRING"

# Copy configuration files
COPY Directory.Build.props ./
COPY Directory.Packages.props ./
COPY stylecop.json ./
COPY .ruleset ./
COPY .editorconfig ./

# Copy solution and .csproj files
COPY Hanamilegal.Web.slnx ./
COPY Api/Hanamilegal.Web.ApplicationsApi/Hanamilegal.Web.ApplicationsApi.csproj Api/Hanamilegal.Web.ApplicationsApi/
COPY Shared/Hanamilegal.Web.ApiConfiguration/Hanamilegal.Web.ApiConfiguration.csproj Shared/Hanamilegal.Web.ApiConfiguration/
COPY Shared/Hanamilegal.Web.Auth/Hanamilegal.Web.Auth.csproj Shared/Hanamilegal.Web.Auth/
COPY Shared/Hanamilegal.Web.Contracts/Hanamilegal.Web.Contracts.csproj Shared/Hanamilegal.Web.Contracts/

# Restore dependencies
RUN dotnet restore Api/Hanamilegal.Web.ApplicationsApi/Hanamilegal.Web.ApplicationsApi.csproj

# Copy sources
COPY Api/Hanamilegal.Web.ApplicationsApi/. Api/Hanamilegal.Web.ApplicationsApi/
COPY Shared/Hanamilegal.Web.ApiConfiguration/. Shared/Hanamilegal.Web.ApiConfiguration/
COPY Shared/Hanamilegal.Web.Auth/. Shared/Hanamilegal.Web.Auth/
COPY Shared/Hanamilegal.Web.Contracts/. Shared/Hanamilegal.Web.Contracts/

# Install dotnet-ef
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"

# Create executable that applies pending migrations
RUN dotnet ef migrations bundle \
    --project Api/Hanamilegal.Web.ApplicationsApi \
    --startup-project Api/Hanamilegal.Web.ApplicationsApi \
    --context ApplicationsDbContext \
    --configuration Release \
    --output /out/efbundle

# Use runtime
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

# Copy migration artifacts
COPY --from=build /out/efbundle /app/efbundle
RUN chmod +x /app/efbundle

# Apply migration
ENTRYPOINT ["/app/efbundle"]
