FROM node:22-alpine

WORKDIR /app

# Copy build configuration
COPY package.json yarn.lock ./

# Install build dependencies
RUN yarn install --frozen-lockfile

# Copy all files
COPY . ./

CMD ["yarn", "start:dev"]
