# Reject unknown domains over HTTP
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    return 444;
}

# Reject unknown domains over HTTPS
server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;

    server_name _;

    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    return 444;
}

# Redirect HTTP requests for known domains to HTTPS
server {
    listen 80;
    listen [::]:80;

    server_name
        hanamilegal.ru
        internal.hanamilegal.ru
        tech.hanamilegal.ru
        accounts.hanamilegal.ru
        applications.hanamilegal.ru;

    return 301 https://$host$request_uri;
}

# Hanamilegal.Web.LegalSupportApp
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name hanamilegal.ru;

    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    location / {
        proxy_pass http://legal-support-app:80;

        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
    }
}

# Hanamilegal.Web.InternalApp
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name internal.hanamilegal.ru;

    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    location / {
        proxy_pass http://internal-app:80;

        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
    }
}

# Hanamilegal.Web.TechApp
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name tech.hanamilegal.ru;

    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    location / {
        proxy_pass http://tech-app:80;

        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
    }
}

# Hanamilegal.Web.AccountsApi
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name accounts.hanamilegal.ru;

    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    location / {
        proxy_pass http://accounts-api:80;

        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
    }
}

# Hanamilegal.Web.ApplicationsApi
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name applications.hanamilegal.ru;

    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    location / {
        proxy_pass http://applications-api:80;

        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
    }
}
