FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

# Install vsdbg for debugging from VS Code
RUN apt-get update \
    && apt-get install -y --no-install-recommends curl unzip \
    && rm -rf /var/lib/apt/lists/* \
    && curl -sSL https://aka.ms/getvsdbgsh \
    | bash /dev/stdin -v latest -l /vsdbg

WORKDIR /app/src

# Copy configuration files
COPY Directory.Build.props ./
COPY Directory.Packages.props ./
COPY stylecop.json ./
COPY .ruleset ./
COPY .editorconfig ./

# Copy solution and .csproj files
COPY Hanamilegal.Web.slnx ./
COPY Applications/Hanamilegal.Web.InternalApp/Hanamilegal.Web.InternalApp.csproj Applications/Hanamilegal.Web.InternalApp/
COPY Shared/Hanamilegal.Web.ApiConfiguration/Hanamilegal.Web.ApiConfiguration.csproj Shared/Hanamilegal.Web.ApiConfiguration/
COPY Shared/Hanamilegal.Web.Auth/Hanamilegal.Web.Auth.csproj Shared/Hanamilegal.Web.Auth/
COPY Shared/Hanamilegal.Web.Contracts/Hanamilegal.Web.Contracts.csproj Shared/Hanamilegal.Web.Contracts/

# Restore dependencies
RUN dotnet restore Applications/Hanamilegal.Web.InternalApp/Hanamilegal.Web.InternalApp.csproj

# Copy sources
COPY Applications/Hanamilegal.Web.InternalApp/. Applications/Hanamilegal.Web.InternalApp/
COPY Shared/Hanamilegal.Web.ApiConfiguration/. Shared/Hanamilegal.Web.ApiConfiguration/
COPY Shared/Hanamilegal.Web.Auth/. Shared/Hanamilegal.Web.Auth/
COPY Shared/Hanamilegal.Web.Contracts/. Shared/Hanamilegal.Web.Contracts/

# Run application
ENTRYPOINT [ \
    "dotnet", "run", \
    "--no-launch-profile", \
    "--project", "Applications/Hanamilegal.Web.InternalApp/Hanamilegal.Web.InternalApp.csproj", \
    "--configuration", "Debug" \
    ]
