<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="../../Shared/Hanamilegal.Web.ApiConfiguration/Hanamilegal.Web.ApiConfiguration.csproj" />
    <ProjectReference Include="../../Shared/Hanamilegal.Web.Auth/Hanamilegal.Web.Auth.csproj" />
    <ProjectReference Include="../../Shared/Hanamilegal.Web.Contracts/Hanamilegal.Web.Contracts.csproj" />
  </ItemGroup>

</Project>
